# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

#[[main]]
 # name = "Home"
  #pageRef = "/"
  #weight = 5

[[main]]
  name = "Self-Care & Wellness"
  weight = 10

[[main]]
  name = "Skincare"
  parent = "Self-Care & Wellness"
  pageRef = "categories/skincare"
  weight = 11
[[main]]
  name = "Bodycare"
  parent = "Self-Care & Wellness"
  pageRef = "categories/bodycare"
  weight = 12
[[main]]
  name = "Mental Health"
  parent = "Self-Care & Wellness"
  pageRef = "categories/mental-health"
  weight = 13
[[main]]
  name = "SelfCare"
  parent = "Self-Care & Wellness"
  pageRef = "categories/self-care"
  weight = 14


[[main]]
  name = "Aesthetic Decor"
  weight = 20

[[main]]
  name = "Home Decor"
  parent = "Aesthetic Decor"
  pageRef = "categories/home-decor"
  weight = 21
[[main]]
  name = "Kitchen Essentials"
  parent = "Aesthetic Decor"
  pageRef = "categories/kitchen-essentials"
  weight = 22
[[main]]
  name = "Bathroom Essentials"
  parent = "Aesthetic Decor"
  pageRef = "categories/bathroom-essentials"
  weight = 23



[[main]]
  name = "Productivity & Learning"
  weight = 25

[[main]]
  name = "Productivity"
  parent = "Productivity & Learning"
  pageRef = "categories/productivity"
  weight = 26
[[main]]
  name = "Learn Korean"
  parent = "Productivity & Learning"
  pageRef = "categories/learn-korean"
  weight = 27


[[main]]
name = "AI Tools & Cool Websites"
weight = 30

[[main]]
name = "AI Tools"
parent = "AI Tools & Cool Websites"
pageRef = "categories/ai-tools"
weight = 31

[[main]]
name = "Cool Websites"
parent = "AI Tools & Cool Websites"
pageRef = "categories/cool-websites"
weight = 32


[[main]]
  name = "Islamic Corner"
  pageRef = "categories/islamic-corner"
  weight = 35


#[[main]]
#  name = "Parent"
#  weight = 20

#[[main]]
#  name = "example sub-menu 1"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
