backend:
  name: github
  repo: PetalLifeStyle/petallifestyle
  branch: main
  auth_type: oauth
  app_id: Ov23liyHXaCokLN8NiOf  # 👈 Replace with your GitHub OAuth Client ID

site_url: https://petallifestyle.pages.dev
media_folder: static/img
public_folder: /img
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }